### ISSUE TITLE
Edge / Windows 10 / Surface Pro 3 issue: 'save and continue' button is inactive

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#838] opened 2018-09-24 15:10 UTC
Reported via email:

I am writing to report an issue with the ‘Save and Continue’ button on the ‘In the Spotlight’ project page available on the LibCrowds website.

When the ‘Theatre Royal, Bristol’ section of the project is accessed in the Edge browser on Windows 10 on a Surface Pro 3 tablet, the ‘Save and Continue’ button at the bottom of the record page appears to be inactive; I have therefore found it impossible to submit a title transcription and move on to the next record.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-23 10:08
Hi Mia, I didn't manage to reproduce the bug with Edge and other browsers on windows 10. We should have access to a Surface Pro for testing next week or the following.  

In the meantime if you have more details about the bug it might be very helpful, e.g.:
- does it happen systematically and with every title or date submission on Surface Pro? Or only sometimes? 
- If it happens under some special conditions, what is the sequence of user actions before you arrive on the page and before you try to click 'Save and Continue'? (it state might depend on other controls/inputs on the page). Is the browser window maximised? Can you send us a screenshot?
- Same couple of questions for MacOs. I imagine it will be easier for us to reproduce and debug on a Mac than on a Surface. Can you tell us which version of MacOs & Safari and whether it is a touchscreen device as well?

**Comment by mialondon** [comment] 2019-08-27 09:26
Hi @geoffroy-noel-ddh, thanks for looking into this! It was reported by a visitor, and I've asked if they can supply more information over email or on this issue.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-27 10:32
Thanks @mialondon was your second message from 17 Jan also relaying issue reported by the same user?

**Comment by geoffroy-noel-ddh** [comment] 2019-08-27 11:16
I've tested a few date transcriptions this morning with Edge on a Surface 4 Pro. I could not reproduce the issue. If you manage to obtain enough details (see above) to reproduce that would be very helpful as I'm afraid, without them, we might not be able to witness it.

**Comment by mialondon** [comment] 2019-08-27 13:16
@geoffroy-noel-ddh which volumes did you try it on? I could ask on twitter for any Surface Pro users to try that (or another new one that actually works). I got an out of office from the person who originally reported it...

**Comment by mialondon** [comment] 2019-08-27 13:17
> 
> 
> Thanks @mialondon was your second message from 17 Jan also relaying issue reported by the same user?

Could you provide a link? It doesn't ring a bell offhand.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-27 13:51
> This also seems to be an issue with other browsers e.g. Safari on MacOS, Firefox on MacOS?

I meant this message about the same issue appearing on other devices and browsers.

I did the tests on the volume I repaired last week, the first on from the current "Take Part" list:

https://www.libcrowds.com/collection/playbills/projects/164/iiif-annotation

**Comment by mialondon** [comment] 2019-08-27 14:38
It's so good to see a working task again! I've tweeted to see if anyone can report bugs.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-27 15:13
Yes, it's really nice to see it working again. Talking of which, when you have time, I'd be very curious to know how the instructions I left in the related ticket (https://github.com/LibCrowds/libcrowds/issues/843) will work for you. Unless I overlooked something I believe you should be able to repair the other volumes.

**Comment by mialondon** [comment] 2019-08-27 15:15
I was going to talk to @harryjmoss about blocking out a good chunk of time to work through them together. I'm in and out of the office for events at the moment, and http://livingwithmachines.ac.uk/ takes up most of the rest of my time.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-27 15:22
No problem. In case that helps, any of your colleagues with admin access to Libcrowds backend should also be able to run through the documented process. When that happens, I'd recommend you try with a single volume and project first to see how it goes and report any problem or question on github/email if you get stuck.

**Comment by mialondon** [comment] 2019-08-27 21:39
I've just tried on my Mac (10.14.3) at home and the 'Save and continue' button isn't active on Firefox 67.0.4. I wasn't logged in.

It also didn't work on Safari 12.0.3, not logged in.

**Comment by geoffroy-noel-ddh** [comment] 2019-08-28 11:36
Thanks Mia, I can now reproduce it systematically with any browser. It looks like the two necessary conditions are: not being logged in & going to libcrowds for the first time after starting the browser. I should be able to look into this bug next week, when I'm back from holidays.

Mia, if you have time could you please check if following temporary work-around works for you?
* after witnessing the bug, just reload the page and try to click the "Save and Continue" button again, this time it should respond to your click.

**Technical notes (for developers)**

How to reproduce this systematically:
1. with Firefox go to libcrowds.com and log out
2. quit then restart firefox (maximised window)
3. go to https://www.libcrowds.com/collection/playbills/projects/164/iiif-annotation
4. click OK to close the tutorial pop-up window
5. now the transcription tool is ready
6. a click on "Save and Continue" button doesn't do anything

Observations:
1. on my screen the mouse cursor changes to "clickable" when I hover over the right half of the button, but a click still doesn't do anything
2. a click doesn't trigger any error in the javascript console
3. after manually reloading the page, the bug disappears and it is possible to submit transcriptions on any number of images from that point on
4. I can reproduce the bug with Chrome (tried new incognito session, without login)
5. the bug occurs even when entering a date before clicking the button

**Comment by mialondon** [comment] 2019-08-29 07:20
Thanks! Unfortunately I'm not now home with my mac until Sunday but I'll try it then.

**Comment by mialondon** [comment] 2019-10-04 14:05
Fixes going live now, thanks to @harryjmoss , so we should be able to confirm soon.

**Comment by harryjmoss** [comment] 2019-10-04 15:22
I've merged the fixes (and one clearing up the travis CI build error) with the master branch, which is now  running on the live site! This also includes an automatic security update detailed [here](https://github.com/LibCrowds/libcrowds/pull/852).

**Closed** 2019-10-15 11:01 UTC
