### ISSUE TITLE
Projects don't load in Chrome/Linux

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#543] opened 2017-11-17 13:31 UTC
See https://twitter.com/jbaiter_/status/931510247155478528 - I'll try to find out more re flavours of Linux etc.

**Comment by jbaiter** [comment] 2017-11-17 13:38
Here's some more info (original reporter from Twitter here):

- Browser: Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)
- No errors on the JS console
- No failed requests
- A Task was successfully fetched:

```
{
  "info": {
    "info": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589068.0x000002/manifest.json",
    "target": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589068.0x000090",
    "form": {
      "model": {
        "date": ""
      },
      "classification": {
        "date": "http://www.w3.org/2001/XMLSchema#date"
      },
      "schema": {
        "fields": [
          {
            "type": "input",
            "model": "date",
            "placeholder": "dd/mm/yyyy",
            "inputType": "text",
            "label": "Date"
          }
        ]
      }
    },
    "guidance": "Type in the main date of the playbill. Put the day date first, then the month, then the year.",
    "shareUrl": "http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589068.0x000002#?cv=53",
    "tileSource": "https://api.bl.uk/image/iiif/ark:/81055/vdc_100022589067.0x000038/info.json",
    "mode": "transcribe",
    "objective": "Transcribe the date",
    "thumbnailUrl": "https://api.bl.uk/image/iiif/ark:/81055/vdc_100022589067.0x000038/full/256,/0/default.jpg",
    "help": "Transcribe the main performance date shown on a playbill to help researchers analyse patterns in performances.\r\n\r\nThe date usually appears in the first few lines of the playbill.\r\n\r\n![Playbill showing date](https://cdn.rawgit.com/LibCrowds/project-playbills/cfe5d1c8/assets/dates_snippet.png)\r\n\r\n- The date format is dd/mm/yyyy - the day of the month goes first, then the month, then the year. In this example, it'd be 29/01/1829\r\n- You don't need to type the day of the week\r\n- Sometimes playbills mention upcoming or past performances - you can ignore them\r\n- If you can't see a date, add a note to let us know\r\n- Be careful not to accidentally transpose numbers and type '1979' instead of '1797' (for example)\r\n- If you're used to American dates, be careful not to mix up the day and month\r\n\r\nIf you have a question that isn't answered here, please post a question on our [discussion forum](https://community.libcrowds.com/t/in-the-spotlight) or on twitter ([@LibCrowds](https://twitter.com/libcrowds)).\r\n"
  },
  "fav_user_ids": null,
  "n_answers": 3,
  "quorum": 0,
  "calibration": 0,
  "created": "2017-11-09T01:44:40.972573",
  "state": "ongoing",
  "project_id": 88,
  "id": 74307,
  "priority_0": 0
}
```

**Comment by mialondon** [comment] 2017-11-17 13:42
Thanks so much, @jbaiter ! @alexandermendes I know you're in the workshop or in transit but let me know when you can check this out

**Comment by alexandermendes** [comment] 2017-11-17 13:59
Ok thanks, I'll have to check it out later - is it just the date projects causing an issue?

**Comment by mialondon** [comment] 2017-11-17 14:01
It's all of the mark or transcribe tasks that I've checked.

**Comment by alexandermendes** [comment] 2017-11-17 14:03
Hmmm, so perhaps a browser thing then. And it looks like you just see a blank page with maybe a skeleton of the layout for the other pages

**Comment by alexandermendes** [comment] 2017-11-17 14:05
Ok I see it now, working on it!

**Comment by alexandermendes** [comment] 2017-11-17 14:09
Might be ok now?

**Comment by jbaiter** [comment] 2017-11-17 14:09
Indeed :-) Works fine now!

**Comment by mialondon** [comment] 2017-11-17 14:10
Hoorah!

**Comment by alexandermendes** [comment] 2017-11-17 14:10
Phew, thanks! Will figure out the cause later

**Comment by alexandermendes** [comment] 2017-11-18 18:14
This was basically a problem with an incorrect identifier when loading the viewer, we should be ok now so closing!

**Closed by alexandermendes** 2017-11-18 18:14 UTC
